language: python

services:
  - docker

before_install:
- docker pull lynngroup/abcfinder:db
- docker pull lynngroup/abcfinder:redis
- docker pull lynngroup/abcfinder:web
- docker pull lynngroup/abcfinder:celery


before_script:
- docker-compose up

# You will want this for logging. If one of your containers does not build for
  # whatever reason it's best to report that now before your tests start
  # otherwise it can be really tricky to debug why tests are failing sometimes.
- docker ps

after_script:
- docker-compose down
