version: '3.4'

services:
  db:
    image: "lynngroup/abcfinder_db:latest"
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
  redis:
    image: "lynngroup/abcfinder_redis:latest"
    volumes:
      - .:/django_app
 
    ports:
      - "6379"
    entrypoint: redis-server --appendonly yes
    restart: always
 
  web:
    image: "lynngroup/abcfinder_web:latest"
    build: .
    command: bash -c "python /django_app/manage.py migrate --noinput && python /django_app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/django_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery
  celery:
    image: "lynngroup/abcfinder_celery:latest"
    build: .
    command: celery --app=webserver worker --loglevel=INFO
    volumes:
      - .:/django_appversion: '3.4'

services:
  db:
    image: "lynngroup/abcfinder:db"
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
  redis:
    image: "lynngroup/abcfinder:redis"
    volumes:
      - .:/django_app
 
    ports:
      - "6379"
    entrypoint: redis-server --appendonly yes
    restart: always
 
  web:
    image: "lynngroup/abcfinder:web"
    build: .
    command: bash -c "python /django_app/manage.py migrate --noinput && python /django_app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/django_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery
  celery:
    image: "lynngroup/abcfinder:celery"
    build: .
    command: celery --app=webserver worker --loglevel=INFO
    volumes:
      - .:/django_app
    depends_on:
      - db
      - redis
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      #   window: 120s
      # replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.60'
          memory: 5G
        reservations:
          cpus: '0.25'
          memory: 2G
volumes:
  redis-data:
    depends_on:
      - db
      - redis
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      #   window: 120s
      # replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.60'
          memory: 5G
        reservations:
          cpus: '0.25'
          memory: 2G
volumes:
  redis-data:
