version: '3.4'

services:
  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
  redis:
    image: "redis:alpine"
  web:
    #image: "django_image:latest"
    build: .
    command: bash -c "python /django_app/manage.py migrate --noinput && python /django_app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/django_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery --app=webserver worker --loglevel=INFO
    volumes:
      - .:/django_app
    depends_on:
      - db
      - redis
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.60'
          memory: 5G
        reservations:
          cpus: '0.25'
          memory: 2G


